apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: sqs-sample
  namespace: default
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: test-chan
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: message-dumper
